### ISSUE TITLE
Analyse einer geeigneten API

### ISSUE THREAD

**Issue by vdemizki** [sgeier96/WBA2SS17DemizkiGeierMuelders#2]
Die alte Analyse ist grob gehalten und geht nicht auf unsere Idee ein.

**Comment by vdemizki** [comment]
Die alte Analyse ist grob gehalten und geht nicht auf unsere Idee ein.

**Comment by vdemizki** [comment]
Netflix api ist nicht mehr verfügbar.
Dafür TMDb-API (The Movie Database) kostenlos verfügbar.
Dazu gibt es die Funktionalität des node.js imdb-api.

**Comment by sgeier96** [comment]
Analyse fertig
